CREATE TABLE USER (
    USERNAME VARCHAR(30) PRIMARY KEY,
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL
);

CREATE TABLE APPOINTMENT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(100) NOT NULL,
    LOCATION VARCHAR(100) NOT NULL,
    DURATION INT NOT NULL,
    DESCRIPTION VARCHAR(1000),
    CREATOR VARCHAR(30) NOT NULL,
    CONSTRAINT FK_APPOINTMENT_CREATOR FOREIGN KEY (CREATOR) REFERENCES USER (USERNAME)
);
ALTER TABLE APPOINTMENT AUTO_INCREMENT = 101;

CREATE TABLE COMMENT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CONTENT VARCHAR(140) NOT NULL,
    CREATION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USER_USERNAME VARCHAR(30) NOT NULL,
    CONSTRAINT FK_COMMENT_USER_USERNAME FOREIGN KEY (USER_USERNAME) REFERENCES USER (USERNAME)
);
ALTER TABLE COMMENT AUTO_INCREMENT = 101;

CREATE TABLE APPOINTMENT_CHOICE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DATE_TIME TIMESTAMP NOT NULL,
    APPOINTMENT_ID INT NOT NULL,
    CONSTRAINT FK_APPOINTMENT_CHOICE_APPOINTMENT_ID FOREIGN KEY (APPOINTMENT_ID) REFERENCES APPOINTMENT (ID)
);
ALTER TABLE APPOINTMENT_CHOICE AUTO_INCREMENT = 101;

CREATE TABLE APPOINTMENT_VOTE (
    APPOINTMENT_CHOICE_ID INT,
    USER_USERNAME VARCHAR(30),
    PRIMARY KEY(APPOINTMENT_CHOICE_ID, USER_USERNAME),
    CONSTRAINT FK_APPOINTMENT_VOTE_APPOINTMENT_CHOICE_ID FOREIGN KEY (APPOINTMENT_CHOICE_ID) REFERENCES APPOINTMENT_CHOICE (ID),
    CONSTRAINT FK_APPOINTMENT_VOTE_USER_USERNAME FOREIGN KEY (USER_USERNAME) REFERENCES USER (USERNAME)
);
ALTER TABLE APPOINTMENT_VOTE AUTO_INCREMENT = 101;