CREATE TABLE APPOINTMENT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(100) NOT NULL,
    LOCATION VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    DURATION INT NOT NULL,
    CREATOR VARCHAR(30) NOT NULL
);
ALTER TABLE APPOINTMENT AUTO_INCREMENT = 101;

CREATE TABLE APPOINTMENT_DATE_TIME (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DATE_TIME BIGINT NOT NULL,
    APPOINTMENT_ID INT NOT NULL,
    CONSTRAINT FK_APPOINTMENT_DATE_TIME_APPOINTMENT_ID FOREIGN KEY (APPOINTMENT_ID) REFERENCES APPOINTMENT (ID)
);
ALTER TABLE APPOINTMENT_DATE_TIME AUTO_INCREMENT = 101;

CREATE TABLE DATE_TIME_VOTE (
    DATE_TIME_ID INT,
    USERNAME VARCHAR(30),
    PRIMARY KEY(DATE_TIME_ID, USERNAME),
    CONSTRAINT FK_DATE_TIME_VOTE_DATE_TIME_ID FOREIGN KEY (DATE_TIME_ID) REFERENCES APPOINTMENT_DATE_TIME (ID)
);
ALTER TABLE DATE_TIME_VOTE AUTO_INCREMENT = 101;

CREATE TABLE COMMENT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CONTENT VARCHAR(140) NOT NULL,
    CREATION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USERNAME VARCHAR(30) NOT NULL,
    APPOINTMENT_ID INT NOT NULL,
    CONSTRAINT FK_COMMENT_APPOINTMENT_ID FOREIGN KEY (APPOINTMENT_ID) REFERENCES APPOINTMENT (ID)
);
ALTER TABLE COMMENT AUTO_INCREMENT = 101;
